### ISSUE TITLE
Differences between README vs Website vs Test

### ISSUE THREAD

**Issue by joelim01** [learn-co-curriculum/ruby-advanced-class-methods-lab#10]
Seems like the README is out of date?

**README:**
song = Song.create("The Middle")
Song.all.include?(song) #=> true

**Web:**
song = Song.create
Song.all.include?(song) #=> true

**Test:**
describe "Song Class Methods" do
  describe '.create' do
    it 'instantiates and saves the song, and it returns the new song that was created' do
      song = Song.create
      expect(song).to be_a(Song)
      expect(Song.all).to include(song)
    end
  end

**Comment by octosteve** [comment]
Fixed 7823dd521fc44dd19461941fcce5182d16989358

**Comment by StevenNunez** [comment]
@pletcher @AnnJohn
