### ISSUE TITLE
the find_by_name tests can pass with incorrect solution 

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/ruby-advanced-class-methods-lab#4]
If you you look at [this line](https://github.com/KhalilC/ruby-advanced-class-methods-lab-v-000/blob/5f51af1496b77b9cb4d27205f378fc8b30c4531a/lib/song.rb#L32). This shouldn't work! It will return true for the very first item, no matter what.

Our find_by_name test needs to have multiple items in it (3+) and then find_by_name on something in the middle!

**Comment by SophieDeBenedetto** [comment]
closed with latest commit
