### ISSUE TITLE
self.alphabetical issue

### ISSUE THREAD

**Issue by CalebKnox** [learn-co-curriculum/ruby-advanced-class-methods-lab#8]
The respec test for alphabetical creates 3 new songs by name and then checks to see if they have been sorted in alphabetical order by self.alphabetical. My issue is that the songs from the previous tests are still in @@all. I can't sort by name because the initial create method shovels a song without a name into @@all. I also can't get past the test since I have more than three songs in the array. Is this normal behavior from the testing suite? If it is, please let me know so that I can go back and refactor some of my previous code to see if that helps anything. Thanks.

**Comment by AnnJohn** [comment]
Hi @CalebKnox thanks for raising this issue. We'll look into it as soon as we can but as far as I know, the tests should be correct. For immediate help with your problem though, please use the Ask a Question tool in Learn and someone from our support team will get back to your right away. Thanks!

**Comment by AnnJohn** [comment]
Hi again @CalebKnox sorry for the continued delay. But for immediate help with this issue, please use the Ask a Question tool in Learn and someone from our support team will help your right away if this is still an issue. Thanks.
